---
title: "Analysis"
format: gfm
---

## Load packages & read data

```{r packages & data}
#| output: false

library(dplyr)
library(data.table)
library(ggplot2)
library(lme4)
library(stargazer)S

data <- fread("../data/moddatafinal_LASTTIMEIPROMISE.csv", drop  = c("ego",
                                                                     "birth_country",
                                                                     "birth_year",
                                                                     "death_year"))

```

## Format data

```{r correct format of variables}
data <- data %>% 
  mutate(
    migrant = factor(migrant, levels = c(0, 1),
                     labels = c("nonmigrant", "migrant")),
    death_country = factor(death_country, levels = c("UK/Ireland", "Canada",
                                                     "South Africa", "Australia",
                                                     "New Zealand",
                                                     "United States of America")),
    birth10 = as.factor(birth10),
    death10 = as.factor(death10),
    gender = as.factor(gender),
    sib_size_cat = as.factor(sib_size_cat),
    birthorder_cat = as.factor(birthorder_cat),
    firstborn = factor(firstborn, levels = c('missing', '0', '1'))
    )
```

## Desctiptive statistics data

```{r descrtiptives}
summary(data$deathage)
```

```{r descrtiptives}
summary(data$migrant)
```

```{r descrtiptives}
table(data$death_country)
```

```{r descrtiptives}
summary(data$birth10)
```

```{r descrtiptives}
summary(data$death10)
```

```{r descrtiptives}
summary(data$gender)
```

```{r descrtiptives}
summary(data$sib_size_cat)
```

```{r descrtiptives}
summary(data$famid)
```

```{r descrtiptives}
table(data$firstborn)
```

## Family effects models

```{r Family effects model - migrant}

# model 1 - migrant
fe1 <- lmer(deathage ~ migrant * birth10 + gender + sib_size_cat + (1|famid),
            data = data) 

summary(fe1)

```


## Death country

```{r Family effects - death country}

# model 2 - destination country
fe2 <- lmer(deathage ~ death_country * birth10 + gender + sib_size_cat + (1|famid),
         data = data)

summary(fe2)

```


```{r stargazer tables - fam effects models}

cov.labs <- c("Migrant", "Canada", "South Africa", "Australia", 
              "New Zealand", "United States of America")
omit.vars <- c("birth10", "sib_size_cat", "gender")

stargazer(fe1, fe2,
                 type = "text",
                 column.labels = c("Migrant", "Country of Death"),
                 covariate.labels = cov.labs,
                 dep.var.caption = "Dependent variable: Age at Death",
                 dep.var.labels = "",
                 keep.stat = c("n"),
                 add.lines=list(c("Sibling random effects", "Yes", "Yes"))
)


```

## Modified sample

```{r newdata}


# make df where everyone has a parent in the data
newdata <- data %>% 
  filter(miss.famid == F) %>% 
  select(-miss.famid)

summary(newdata$sib_size_cat)

rm(data)


```

```{r alt migrant - modified samples fe1}

omit.vars <- c("birth10", "sib_size_cat", "gender")

fe1.lim <- lmer(deathage ~ migrant * birth10 + gender + sib_size_cat + (1|famid),
         data = newdata) 
summary(fe1.lim)

newdata %>% 
  ggplot(aes(
    x = predict(fe1.lim),
    y = deathage)) + 
  geom_point() + 
  geom_abline(
    intercept = 0,
    slope = 1) +
  scale_x_continuous(limits = c(15, 110)) +
  scale_y_continuous(limits = c(15, 110)) +
  labs(x='Predicted Values', 
       y='Actual Values', 
       title='Predicted vs. Actual Values',
       subtitle= 'migrant - model 2 - have parents')

fe2.lim <- lmer(deathage ~ death_country * birth10 + gender + sib_size_cat + (1|famid),
         data = newdata) 
summary(fe2.lim)

plot_predictions(fe2.lim, by = "death_country") 

newdata %>% 
  ggplot(aes(
    x = predict(fe2.lim),
    y = deathage)) + 
  geom_point() + 
  geom_abline(
    intercept = 0,
    slope = 1) +
  scale_x_continuous(limits = c(15, 110)) +
  scale_y_continuous(limits = c(15, 110)) +
  labs(x='Predicted Values', 
       y='Actual Values', 
       title='Predicted vs. Actual Values',
       subtitle= 'death country - model 2 - have parents')



```

```{r newdata}

# make df where only people with siblings are in data
newerdata <- newdata %>% 
  filter(sib.ct > 0)

rm(newdata)

```

```{r alt migrant - modified samples fe2}

fe1.sibs <- lmer(deathage ~ migrant * birth10 + gender + sib_size_cat + (1|famid),
         data = newerdata) 
summary(fe1.sibs)

newerdata %>% 
  ggplot(aes(
    x = predict(fe1.sibs),
    y = deathage)) + 
  geom_point() + 
  geom_abline(
    intercept = 0,
    slope = 1) +
  scale_x_continuous(limits = c(15, 110)) +
  scale_y_continuous(limits = c(15, 110)) +
  labs(x='Predicted Values', 
       y='Actual Values', 
       title='Predicted vs. Actual Values',
       subtitle= 'migrant - model 3 - have parents + siblings')

stargazer(fe1, fe1.lim, fe1.sibs,
          type = "text",
          column.labels = c("full", "have parents", "have siblings"),
          dep.var.caption = "Dependent variable: Age at Death",
          dep.var.labels = "",
          omit = omit.vars)

fe2.sibs <- lmer(deathage ~ death_country * birth10 + gender + sib_size_cat + (1|famid),
         data = newerdata) 
summary(fe2.sibs)

plot_predictions(fe2.sibs, by = "death_country")

newerdata %>% 
  ggplot(aes(
    x = predict(fe2.sibs),
    y = deathage)) + 
  geom_point() + 
  geom_abline(
    intercept = 0,
    slope = 1) +
  scale_x_continuous(limits = c(15, 110)) +
  scale_y_continuous(limits = c(15, 110)) +
  labs(x='Predicted Values', 
       y='Actual Values', 
       title='Predicted vs. Actual Values',
       subtitle= 'death country - model 3 - have parents + siblings')

stargazer(fe1, fe1.lim, fe1.sibs, fe2, fe2.lim, fe2.sibs,
          type = "text",
          column.labels = c("full", "have parents", "have siblings",
                            "full", "have parents", "have siblings"),
          dep.var.caption = "Dependent variable: Age at Death",
          dep.var.labels = "")


```

